apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: wisecow
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
      - path: "/bin/sh"
        action: Block
  file:
    matchPaths:
      - path: "/etc/*"
        action: Block

